# ============================================================
# IT Procurement Automation — Setup Wizard
# ============================================================
# Guides first-time configuration of config.yaml and .env
# Run from project root:
#   python -m src.setup_wizard

import os
import yaml
import smtplib
from email.mime.text import MIMEText
from pathlib import Path


# ------------------------------------------------------------
# Helpers
# ------------------------------------------------------------

def clear():
    os.system("cls" if os.name == "nt" else "clear")


def header():
    print("=" * 52)
    print("  IT Procurement Automation")
    print("  Setup Wizard")
    print("=" * 52)


def section(title: str):
    print(f"\n  ── {title} {'─' * (40 - len(title))}")


def ask(prompt: str, default: str = "") -> str:
    """Asks for input with an optional default value."""
    if default:
        value = input(f"  {prompt} [{default}]: ").strip()
        return value if value else default
    return input(f"  {prompt}: ").strip()


def ask_password(prompt: str) -> str:
    """Asks for a password — shown as input for simplicity."""
    return input(f"  {prompt}: ").strip()


def success(msg: str):
    print(f"\n  ✅ {msg}")


def warning(msg: str):
    print(f"\n  ⚠️  {msg}")


def error(msg: str):
    print(f"\n  ❌ {msg}")


def pause():
    input("\n  Press Enter to continue...")


# ------------------------------------------------------------
# Config updater
# ------------------------------------------------------------

def update_config(updates: dict, config_path: str = "config.yaml") -> None:
    """Updates specific fields in config.yaml."""
    with open(config_path, "r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    # Deep merge updates into config
    for section_key, values in updates.items():
        if section_key not in cfg:
            cfg[section_key] = {}
        if isinstance(values, dict):
            cfg[section_key].update(values)
        else:
            cfg[section_key] = values

    with open(config_path, "w", encoding="utf-8") as f:
        yaml.dump(cfg, f, allow_unicode=True, default_flow_style=False, sort_keys=False)


def write_env(values: dict, env_path: str = ".env") -> None:
    """Writes or updates variables in .env file."""
    existing = {}

    # Read existing values if file exists
    if Path(env_path).exists():
        with open(env_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, _, val = line.partition("=")
                    existing[key.strip()] = val.strip()

    # Merge new values
    existing.update(values)

    # Define section order
    sections = {
        "Jira": ["JIRA_URL", "JIRA_USER", "JIRA_API_TOKEN", "JIRA_MOCK"],
        "Netsuite": [
            "NETSUITE_ACCOUNT_ID", "NETSUITE_CONSUMER_KEY",
            "NETSUITE_CONSUMER_SECRET", "NETSUITE_TOKEN_ID",
            "NETSUITE_TOKEN_SECRET", "NETSUITE_MOCK"
        ],
        "Vendor": ["VENDOR_URL", "VENDOR_USER", "VENDOR_PASSWORD", "VENDOR_MOCK"],
        "Notifications": [
            "NOTIFY_EMAIL", "NOTIFY_EMAIL_SENDER", "NOTIFY_EMAIL_PASSWORD",
            "NOTIFY_SMTP_HOST", "NOTIFY_SMTP_PORT", "NOTIFY_MOCK",
            "NOTIFY_SLACK", "NOTIFY_TEAMS",
            "SLACK_WEBHOOK_URL", "TEAMS_WEBHOOK_URL", "FINANCE_TEAM_EMAIL"
        ],
    }

    with open(env_path, "w", encoding="utf-8") as f:
        f.write("# IT Procurement Automation - Environment Variables\n")
        f.write("# Generated by setup wizard\n\n")

        written = set()
        for section_name, keys in sections.items():
            section_values = {k: existing[k] for k in keys if k in existing}
            if section_values:
                f.write(f"# {section_name}\n")
                for key, val in section_values.items():
                    f.write(f"{key}={val}\n")
                    written.add(key)
                f.write("\n")

        # Write any remaining keys not in sections
        remaining = {k: v for k, v in existing.items() if k not in written}
        if remaining:
            f.write("# Other\n")
            for key, val in remaining.items():
                f.write(f"{key}={val}\n")


# ------------------------------------------------------------
# Setup sections
# ------------------------------------------------------------

def setup_company() -> dict:
    """Collects company information."""
    section("Company Information")
    print()

    name = ask("Company name", "Your Company Name")
    country = ask("Country code (e.g. MX, US, CO)", "MX")
    timezone = ask("Timezone", "America/Mexico_City")

    update_config({
        "company": {
            "name": name,
            "country": country,
            "timezone": timezone,
        }
    })

    success(f"Company configured: {name}")
    return {"name": name}


def setup_jira() -> bool:
    """Collects and tests Jira credentials."""
    section("Jira Configuration")
    print()
    print("  Get your API token at: id.atlassian.com/manage-profile/security/api-tokens\n")

    url = ask("Jira URL (e.g. https://yourcompany.atlassian.net)")
    user = ask("Jira email")
    token = ask_password("Jira API token")
    project_key = ask("Jira project key (e.g. IT-PURCHASE)")

    # Test connection
    print("\n  Testing Jira connection...")
    try:
        from jira import JIRA
        client = JIRA(server=url, basic_auth=(user, token))
        client.myself()
        success("Jira connected successfully.")
        connected = True
    except Exception as e:
        error(f"Could not connect to Jira: {e}")
        warning("Credentials saved but connection failed. Verify and re-run wizard.")
        connected = False

    write_env({
        "JIRA_URL": url,
        "JIRA_USER": user,
        "JIRA_API_TOKEN": token,
        "JIRA_MOCK": "false" if connected else "true",
    })

    update_config({
        "ticket": {
            "project_key": project_key,
        }
    })

    return connected


def setup_email() -> bool:
    """Collects and tests email credentials."""
    section("Email Notifications")
    print()
    print("  For Gmail: use an App Password, not your regular password.")
    print("  Generate at: myaccount.google.com/apppasswords\n")

    sender = ask("Sender email address")
    password = ask_password("Email password or App Password")
    smtp_host = ask("SMTP host", "smtp.gmail.com")
    smtp_port = ask("SMTP port", "587")
    test_recipient = ask("Send test email to")

    # Test connection
    print("\n  Sending test email...")
    try:
        msg = MIMEText(
            "This is a test email from IT Procurement Automation.\n\n"
            "If you received this, your email configuration is working correctly."
        )
        msg["Subject"] = "[IT Procurement] Setup Test"
        msg["From"] = sender
        msg["To"] = test_recipient

        with smtplib.SMTP(smtp_host, int(smtp_port)) as server:
            server.starttls()
            server.login(sender, password)
            server.sendmail(sender, test_recipient, msg.as_string())

        success(f"Test email sent to {test_recipient}")
        connected = True
    except Exception as e:
        error(f"Could not send email: {e}")
        warning("Credentials saved but email failed. Verify and re-run wizard.")
        connected = False

    write_env({
        "NOTIFY_EMAIL": "true",
        "NOTIFY_EMAIL_SENDER": sender,
        "NOTIFY_EMAIL_PASSWORD": password,
        "NOTIFY_SMTP_HOST": smtp_host,
        "NOTIFY_SMTP_PORT": smtp_port,
        "NOTIFY_MOCK": "false" if connected else "true",
    })

    return connected


def setup_netsuite() -> None:
    """Collects Netsuite credentials — no live test."""
    section("Netsuite Configuration")
    print()
    warning("Netsuite requires company network access to test.")
    print("  Credentials will be saved — verify connection from work PC.\n")

    account_id = ask("Netsuite Account ID")
    consumer_key = ask_password("Consumer Key")
    consumer_secret = ask_password("Consumer Secret")
    token_id = ask_password("Token ID")
    token_secret = ask_password("Token Secret")

    write_env({
        "NETSUITE_ACCOUNT_ID": account_id,
        "NETSUITE_CONSUMER_KEY": consumer_key,
        "NETSUITE_CONSUMER_SECRET": consumer_secret,
        "NETSUITE_TOKEN_ID": token_id,
        "NETSUITE_TOKEN_SECRET": token_secret,
        "NETSUITE_MOCK": "true",
    })

    warning("Netsuite saved. Set NETSUITE_MOCK=false once verified on company network.")


def setup_vendor() -> None:
    """Collects vendor portal credentials — no live test."""
    section("Vendor Portal Configuration")
    print()
    warning("Vendor scraping requires Playwright browser installation.")
    print("  Run after setup: playwright install chromium\n")

    url = ask("Vendor portal URL")
    user = ask("Vendor login email")
    password = ask_password("Vendor password")

    write_env({
        "VENDOR_URL": url,
        "VENDOR_USER": user,
        "VENDOR_PASSWORD": password,
        "VENDOR_MOCK": "true",
    })

    warning("Vendor saved. Run 'playwright install chromium' then set VENDOR_MOCK=false.")


# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

def print_summary(results: dict) -> None:
    """Prints configuration summary."""
    clear()
    header()
    print("\n  SETUP COMPLETE\n")
    print("  " + "─" * 46)

    status_map = {
        True: "✅ Connected",
        False: "⚠️  Saved — verify credentials",
        "pending": "⏳ Pending — configure on company network",
        "configured": "✅ Configured",
    }

    for item, status in results.items():
        label = status_map.get(status, str(status))
        print(f"  {item:<20} {label}")

    print("  " + "─" * 46)
    print("\n  Run the system with:")
    print("  python -m src.cli\n")


# ------------------------------------------------------------
# Main wizard flow
# ------------------------------------------------------------

def main():
    clear()
    header()
    print("\n  Welcome! This wizard will configure your environment.")
    print("  You can re-run it anytime to update your settings.\n")

    # Check if .env already exists
    if Path(".env").exists():
        print("  An existing .env file was found.")
        reconfigure = ask("Reconfigure existing setup? (y/n)", "n")
        if reconfigure.lower() != "y":
            print("\n  Setup cancelled. Run 'python -m src.cli' to start.")
            return

    results = {}

    # Company
    pause()
    clear()
    header()
    company = setup_company()
    results["Company"] = "configured"

    # Jira
    pause()
    clear()
    header()
    jira_ok = setup_jira()
    results["Jira"] = jira_ok

    # Email
    pause()
    clear()
    header()
    email_ok = setup_email()
    results["Email"] = email_ok

    # Netsuite
    pause()
    clear()
    header()
    print("\n  Do you have your Netsuite credentials available?")
    has_netsuite = ask("Configure Netsuite now? (y/n)", "n")
    if has_netsuite.lower() == "y":
        setup_netsuite()
        results["Netsuite"] = "pending"
    else:
        write_env({"NETSUITE_MOCK": "true"})
        results["Netsuite"] = "pending"

    # Vendor
    pause()
    clear()
    header()
    print("\n  Do you have your vendor portal credentials available?")
    has_vendor = ask("Configure vendor portal now? (y/n)", "n")
    if has_vendor.lower() == "y":
        setup_vendor()
        results["Vendor portal"] = "pending"
    else:
        write_env({"VENDOR_MOCK": "true"})
        results["Vendor portal"] = "pending"

    # Slack / Teams
    write_env({
        "NOTIFY_SLACK": "false",
        "NOTIFY_TEAMS": "false",
        "SLACK_WEBHOOK_URL": "",
        "TEAMS_WEBHOOK_URL": "",
        "FINANCE_TEAM_EMAIL": "",
    })

    # Summary
    pause()
    print_summary(results)


if __name__ == "__main__":
    main()